export const get_articleListOfFriend_success = 'get_articleListOfFriend_success'
export const get_articleListOfFriend_failed = 'get_articleListOfFriend_failed'
export const get_articleListOfFriend_waiting = 'get_articleListOfFriend_waiting'

export const get_articleListOfFriendMore_success = 'get_articleListOfFriendMore_success'
export const get_articleListOfFriendMore_failed = 'get_articleListOfFriendMore_failed'
export const get_articleListOfFriendMore_waiting = 'get_articleListOfFriendMore_waiting'