export const get_vCodeForRetrievePassword_success = "get_vCodeForRetrievePassword_success"
export const get_vCodeForRetrievePassword_waiting = "get_vCodeForRetrievePassword_waiting"
export const get_vCodeForRetrievePassword_failed = "get_vCodeForRetrievePassword_failed"