export const get_followingListForHome_success = 'get_followingListForHome_success'
export const get_followingListForHome_failed = 'get_followingListForHome_failed'
export const get_followingListForHome_waiting = 'get_followingListForHome_waiting'

export const get_followingListForHomeMore_success = 'get_followingListForHomeMore_success'
export const get_followingListForHomeMore_failed = 'get_followingListForHomeMore_failed'
export const get_followingListForHomeMore_waiting = 'get_followingListForHomeMore_waiting'

export const get_followingUserListForHome_success = 'get_followingUserListForHome_success'
export const get_followingUserListForHome_failed = 'get_followingUserListForHome_failed'
export const get_followingUserListForHome_waiting = 'get_followingUserListForHome_waiting'