export const get_commentForTextArticleInfo_success = 'get_msgCommentForTextArticleInfo_success'
export const get_commentForTextArticleInfo_failed = 'get_msgCommentForTextArticleInfo_failed'
export const get_commentForTextArticleInfo_waiting = 'get_msgCommentForTextArticleInfo_waiting'

export const get_commentForTextArticleInfoMore_success = 'get_commentForTextArticleInfoMore_success'
export const get_commentForTextArticleInfoMore_failed = 'get_commentForTextArticleInfoMore_failed'
export const get_commentForTextArticleInfoMore_waiting = 'get_commentForTextArticleInfoMore_waiting'

export const get_textArticleInfo_success = 'get_textArticleInfo_success'
export const get_textArticleInfo_failed = 'get_textArticleInfo_failed'
export const get_textArticleInfo_waiting = 'get_textArticleInfo_waiting'

export const like_commentForTextArticleInfo_success = 'like_commentForTextArticleInfo_success'
export const like_commentForTextArticleInfo_failed = 'like_commentForTextArticleInfo_failed'
export const like_commentForTextArticleInfo_waiting = 'like_commentForTextArticleInfo_waiting'