export const get_nearbyListForHome_success = 'get_nearbyListForHome_success'
export const get_nearbyListForHome_failed = 'get_nearbyListForHome_failed'
export const get_nearbyListForHome_waiting = 'get_nearbyListForHome_waiting'

export const get_nearbyListForHomeMore_success = 'get_nearbyListForHomeMore_success'
export const get_nearbyListForHomeMore_failed = 'get_nearbyListForHomeMore_failed'
export const get_nearbyListForHomeMore_waiting = 'get_nearbyListForHomeMore_waiting'