export const get_vCodeForUserRegister_success = "get_vCodeForUserRegister_success"
export const get_vCodeForUserRegister_waiting = "get_vCodeForUserRegister_waiting"
export const get_vCodeForUserRegister_failed = "get_vCodeForUserRegister_failed"

export const countDownForUserRegister_start = 'countDownForUserRegister_start'
export const countDownForUserRegister_end = 'countDownForUserRegister_end'