export const get_vCodeForChangePassword_success = "get_vCodeForChangePassword_success"
export const get_vCodeForChangePassword_waiting = "get_vCodeForChangePassword_waiting"
export const get_vCodeForChangePassword_failed = "get_vCodeForChangePassword_failed"

export const countDownForChangePassword_start = 'countDownForChangePassword_start'
export const countDownForChangePassword_end = 'countDownForChangePassword_end'