export const get_vCodeForRetrievePassword_success = "get_vCodeForRetrievePassword_success"
export const get_vCodeForRetrievePassword_waiting = "get_vCodeForRetrievePassword_waiting"
export const get_vCodeForRetrievePassword_failed = "get_vCodeForRetrievePassword_failed"

export const countDownForRetrievePassword_start = 'countDownForRetrievePassword_start'
export const countDownForRetrievePassword_end = 'countDownForRetrievePassword_end'